name: 'Ninja i18n'
description: 'Automatic i18n checks, issue reports and correction workflow for your pull requests'
author: 'opral'
branding:
  icon: 'globe'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - name: Checkout target
      id: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: target
  
    - name: Get merge commit sha from PR
      shell: bash
      run: |
        merge_commit_sha=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
          | jq -r '.merge_commit_sha')
        echo "merge_commit_sha=${merge_commit_sha}" >> $GITHUB_ENV
      id: get-merge-sha
  
    - name: Checkout merge
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get-merge-sha.outputs.merge_commit_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: merge
        
    - name: Run Ninja linting
      main: index.cjs
