name: 'Ninja i18n'
description: 'Automatic i18n checks, issue reports and correction workflow for your pull requests'
author: 'opral'
branding:
  icon: 'globe'
  color: 'gray-dark'

runs:
  using: node20
  steps:
    - name: Run Ninja linting
      main: dist/index.cjs
